host: 127.0.0.1
port: 8080
log_level: info
drs_self_url: drs://localhost:8080/
api_route: /ga4gh/drs/v1
custom_spec_url: null
rabbitmq_host: rabbitmq
rabbitmq_port: 5672
topic_name_download_requested: download_request
db_url: postgresql://admin:admin@postgresql/storage
s3_url: http://s3-localstack:4566

workers: 1
auto_reload: true

cors_allowed_origins: []
cors_allow_credentials: False
cors_allowed_methods: []
cors_allowed_headers: []
