"""Switched drs_id to file_id, made size nullable

Revision ID: dda104bd723f
Revises: 7854bc67c695
Create Date: 2021-12-09 08:30:53.586416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dda104bd723f"
down_revision = "7854bc67c695"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drs_objects", sa.Column("file_id", sa.String(), nullable=False))
    op.alter_column("drs_objects", "size", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("drs_objects_external_id_key", "drs_objects", type_="unique")
    op.create_unique_constraint(None, "drs_objects", ["file_id"])
    op.drop_column("drs_objects", "external_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drs_objects",
        sa.Column("external_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "drs_objects", type_="unique")
    op.create_unique_constraint(
        "drs_objects_external_id_key", "drs_objects", ["external_id"]
    )
    op.alter_column("drs_objects", "size", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("drs_objects", "file_id")
    # ### end Alembic commands ###
